doctrine:
    dbal:
        default_connection: default
        connections:
            default:
                driver:   pdo_mysql
                host:     '%env(BDD_DEFAULT_HOST)%'
                port:     '%env(BDD_DEFAULT_PORT)%'
                dbname:   '%env(BDD_DEFAULT_DBNAME)%'
                user:     '%env(BDD_DEFAULT_USERNAME)%'
                password: '%env(BDD_DEFAULT_PASS)%'
                charset:  UTF8
                options:
                    1002: 'SET sql_mode=(SELECT REPLACE(@@sql_mode, "ONLY_FULL_GROUP_BY", ""))'
    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true
        mappings:
            App:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/Entity'
                prefix: 'App\Entity'
                alias: App
