liip_imagine:
  resolvers:
    default:
      web_path:
        web_root: ~ # %kernel.project_dir%/public (%kernel.project_dir%/web for Symfony < 4.0.0)
        cache_prefix: ~ # media/cache

    loaders:
      default:
        filesystem:
          data_root: ~  # %kernel.project_dir%/public (%kernel.project_dir%/web for Symfony < 4.0.0)

  # As mentioned above, gd, imagick or gmagick are possible
  driver: "gd"
  cache: default
  data_loader: default
  # This is where all the filters sets are located
  filter_sets:
    admin_gallery:
      quality: 70
      filters:
        watermark:
          image: ../public/images/static/watermark.png
          size: 0.2
          position: bottomright

    admin_thumbnail:
      quality: 70
      filters:
        thumbnail: { size: [1200, 1200], mode: outbound }

    gallery_portrait:
      quality: 80
      filters:
        thumbnail: { size: [1200, 1000], mode: inset }

    gallery_panoramique:
      filters:
        thumbnail: { size: [3000, 1000], mode: outbound }

    gallery_landscape:
      quality: 80
      filters:
        thumbnail: { size: [1200, 800], mode: outbound }

    thumbnail:
      filters:
        thumbnail: { size: [1200, 800], mode: outbound }

    thumbnail_category:
      filters:
        thumbnail: { size: [1200, 1000], mode: inset }

    standard:
      quality: 80

    big:
      quality: 60
      filters:
        watermark:
          image: ../public/images/static/watermark.png
          size: 0.2
          position: bottomright