liip_imagine:
  # As mentioned above, gd, imagick or gmagick are possible
  driver: "gd"
  # This is where all the filters sets are located
  filter_sets:
    admin:
      quality: 70
      filters:
        watermark:
          image: ../public/images/static/watermark.png
          size: 0.2
          position: bottomright

    gallery_portrait:
      quality: 80
      filters:
        thumbnail: { size: [1200, 1000], mode: inset }

    gallery_panoramique:
      filters:
        thumbnail: { size: [3000, 1000], mode: outbound }

    gallery_landscape:
      quality: 80
      filters:
        thumbnail: { size: [1200, 800], mode: outbound }

    thumbnail:
      filters:
        thumbnail: { size: [1200, 800], mode: outbound }

    thumbnail_category:
      filters:
        thumbnail: { size: [1200, 1000], mode: inset }

    standard:
      quality: 80

    big:
      quality: 60
      filters:
        watermark:
          image: ../public/images/static/watermark.png
          size: 0.2
          position: bottomright