# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    photo_directory: '%kernel.project_dir%/public/images/uploads/'

fidry_alice_data_fixtures:
    default_purge_mode: 'truncate'

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/*'
        exclude: '../src/{DependencyInjection,Entity,Migrations,Tests,Kernel.php}'

    App\Service\Tools\FileUploaderService:
        arguments:
            $targetDirectory: '%photo_directory%'

    App\Service\Tools\NotificationService:
        arguments:
            $config:
                user: '%env(MAILER_USER)%'

    # controllers are imported separately to make sure services can be injected
    # as action arguments even if you don't extend any base controller class
    App\Controller\:
        resource: '../src/Controller'
        tags: ['controller.service_arguments']

    App\EventListener\WebApp\UserEntityListener:
        class: App\EventListener\WebApp\UserEntityListener
        tags:
            - { name: doctrine.event_listener, event: preUpdate }
            - { name: doctrine.event_listener, event: prePersist }

    App\EventListener\WebApp\TagEntityListener:
        class: App\EventListener\WebApp\TagEntityListener
        tags:
            - { name: doctrine.event_listener, event: preUpdate }
            - { name: doctrine.event_listener, event: prePersist }

    App\EventListener\WebApp\SeasonEntityListener:
        class: App\EventListener\WebApp\SeasonEntityListener
        tags:
            - { name: doctrine.event_listener, event: preUpdate }
            - { name: doctrine.event_listener, event: prePersist }

    App\EventListener\WebApp\TypeEntityListener:
        class: App\EventListener\WebApp\TypeEntityListener
        tags:
            - { name: doctrine.event_listener, event: preUpdate }
            - { name: doctrine.event_listener, event: prePersist }

    App\EventListener\WebApp\CategoryEntityListener:
        class: App\EventListener\WebApp\CategoryEntityListener
        tags:
            - { name: doctrine.event_listener, event: preUpdate }
            - { name: doctrine.event_listener, event: prePersist }

    App\EventListener\WebApp\CommentEntityListener:
        class: App\EventListener\WebApp\CommentEntityListener
        tags:
            - { name: doctrine.event_listener, event: preUpdate }
            - { name: doctrine.event_listener, event: prePersist }

    App\EventListener\WebApp\PhotoEntityListener:
        class: App\EventListener\WebApp\PhotoEntityListener
        tags:
            - { name: doctrine.event_listener, event: preUpdate }
            - { name: doctrine.event_listener, event: prePersist }
            - { name: doctrine.event_listener, event: preRemove }

    app.menu_builder:
        class: App\Menu\MenuBuilder

    app.menu.main:
        class: Knp\Menu\MenuItem
        factory: ['@app.menu_builder', 'main']
        tags:
            - { name: knp_menu.menu, alias: main }

    twig.extension.intl:
        class: Twig_Extensions_Extension_Intl
        tags:
            - { name: twig.extension }

    twig.extension.date:
        class: Twig_Extensions_Extension_Date
        arguments: ["@translator"]
        tags:
            - { name: twig.extension }

